### ISSUE TITLE
Create dictionary of statutes from UCCS schema

### ISSUE THREAD

**Issue by newswim** [open-austin/indigent-defense-stats#67]
Today, when we normalize statute data we send a CSV containing the unprocessed charge data to the University of Michigan and they send us back a processed CSV. Since we have a record of the inputs and outputs, we should be able to create a dictionary to map unprocessed strings to their processed strings, based on the case number and charge.

If this step throws an error, like "Statute not found", we'll add that string to a new data set and send it to U of Mich for processing.

@emilyrbartha should have access to `uccs_schema.csv`.

**Comment by nicolassaw** [comment]
I created a dictionary of statutes as a JSON file and uploaded it to this repo under the cleaning folder suggested [here](https://github.com/open-austin/indigent-defense-stats/pull/85).

To answer my own previous question: This University of Michigan tool is not something can be used via API. It's performed only on CSVs. Accordingly, we'll have to use our largest dataset to match as many as we can, and may be able to use other cleaning methods to capture missed charges.

Accordingly, this item can be closed.
