### ISSUE TITLE
Parse disposition data from HTML

### ISSUE THREAD

**Issue by newswim** [open-austin/indigent-defense-stats#69]

**Comment by nicolassaw** [comment]
This step involves parsing complex disposition data. There may be multiple sentences on a given case in instances where, for example, a person was serving a probation sentence for 2 years but then their probation was revoked and they were sentenced to 180 days in jail. This is two separate sentences in chronological order. For data analysis purposes and visualization, it may make sense to "flatten" the data to only show the first disposition on the case.

This ticket is for parsing the data. The other ticket is for visualizing it.
