### ISSUE TITLE
Parse SID from Odyssey case file

### ISSUE THREAD

**Issue by emilyrbartha** [open-austin/indigent-defense-stats#81]
The `SID` is a identifier that is generated by the Department of Public Safety. It is unique for every person who is issued any kind of citation. It is a state-level identifier so it is also unique across records from different counties.

**Comment by nicolassaw** [comment]
Actually, I am confirming with the parser code that it already parses SID to JSON:

Line 102 of the [parser](https://github.com/open-austin/indigent-defense-stats/blob/main/src/parser/pre2017.py):

`"SID": defendant_rows[1][-1] if len(defendant_rows) > 1 else "",`

Accordingly, I'm closing this ticket.
