### ISSUE TITLE
Parser defense attorney information (name, appointed, bar number, etc.)

### ISSUE THREAD

**Issue by mscarey** [open-austin/indigent-defense-stats#83]
see the `party_information` variable

**Comment by nicolassaw** [comment]
It looks like from the data (some spot checks) that a lot of defense attorney data is missing. It would be important to be able to distinguish between appointed and retained and to link attorneys to multiple cases.

**Comment by nicolassaw** [comment]
Based on a week sample, it looks like the parser is grabbing the field properly. There are large gaps in attorney name and type where there is no attorney listed at all. This can be closed.
