### ISSUE TITLE
Write step that turns the JSON into a tabular format that handles nesting

### ISSUE THREAD

**Issue by nicolassaw** [open-austin/indigent-defense-stats#86]
Currently I wrote a small test code that get a folder filled with JSON and then writes them as rows to an excel sheet. The challenge is pulling fields out of nested items in the JSON array. For example, "party_information" is an array within the main array for the JSON and stores fields like attorney name, whether it is appointed or private, etc.

I'll upload once I get farther with it.

**Comment by normaljosh** [comment]
@nicolassaw are you sure this step is necessary? Cosmosdb is capable of querying nested json data

**Comment by nicolassaw** [comment]
@normaljosh I just spent some time learning how to push entries to CosmosDB, storing authentication credentials in an environment file, and then blocking those from git using gitignore.

Paul, Aaron and I initially discussed a table to keep things simple but I think using CosmoDB ie, storing as JSON in this cloud database makes more sense for the shape of data we're working with. One thing I also need to learn more about is how Nidhi's visualization is reading from the CosmosDB.

I'll close this ticket. Thanks, Josh!
